del /s /q "Output\Launcher\*.pdb"
del /s /q "Output\Launcher\*.xml"
del /s /q "Output\Launcher\*.exp"
del /s /q "Output\Launcher\*.lib"
del /s /q "Output\Launcher\*.iobj"
del /s /q "Output\Launcher\*.ipdb"
